[package]
name = "RustBerry-PoE-Monitor"
version = "0.1.0"
edition = "2021"
authors = ["jackra1n"]
description = "A simple PoE Monitor for Raspberry Pi Waveshare PoE HAT (B)"
repository = "hhttps://github.com/jackra1n/RustBerry-PoE-Monitor"
readme = "README.md"