[package]
name = "RustBerry-PoE-Monitor"
version = "0.1.0"
edition = "2021"
authors = ["jackra1n"]
description = "A simple PoE Monitor for Raspberry Pi Waveshare PoE HAT (B)"
repository = "hhttps://github.com/jackra1n/RustBerry-PoE-Monitor"
readme = "README.md"

[dependencies]
rppal = "0.15.0"
sysinfo = "0.29.10"
ssd1306 = "0.8.4"
embedded-graphics = "0.8.1"
get_if_addrs = "0.5.3"
